2020-10-11 14:21:24,659 INFO: Microblog startup [in /Users/aaron/Code/flask-book/app/__init__.py:45]
2020-10-11 14:21:32,050 INFO: Microblog startup [in /Users/aaron/Code/flask-book/app/__init__.py:45]
2020-10-11 14:36:17,115 INFO: Microblog startup [in /Users/aaron/Code/flask-book/app/__init__.py:45]
2020-10-11 14:48:07,935 INFO: Microblog startup [in /Users/aaron/Code/flask-book/app/__init__.py:45]
2020-10-11 14:53:06,474 INFO: Microblog startup [in /Users/aaron/Code/flask-book/app/__init__.py:45]
2020-11-07 15:12:42,961 INFO: Microblog startup [in /Users/aaron/Code/flask-book/app/__init__.py:47]
2020-11-08 14:10:48,206 INFO: Microblog startup [in /Users/aaron/Code/flask-book/app/__init__.py:47]
2020-11-08 15:08:11,242 INFO: Microblog startup [in /Users/aaron/Code/flask-book/app/__init__.py:47]
2020-11-08 15:08:33,689 ERROR: Exception on /reset_password_request [POST] [in /Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aaron/Code/flask-book/app/routes.py", line 154, in reset_password_request
    send_password_reset_email(user)
  File "/Users/aaron/Code/flask-book/app/email.py", line 13, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
NameError: name 'send_email' is not defined
2020-11-08 15:09:00,928 INFO: Microblog startup [in /Users/aaron/Code/flask-book/app/__init__.py:47]
2020-11-08 15:09:11,102 ERROR: Exception on /reset_password_request [POST] [in /Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aaron/Code/flask-book/app/routes.py", line 154, in reset_password_request
    send_password_reset_email(user)
  File "/Users/aaron/Code/flask-book/app/email.py", line 14, in send_password_reset_email
    sender=app.config['ADMINS'][0],
NameError: name 'app' is not defined
2020-11-08 15:09:51,727 INFO: Microblog startup [in /Users/aaron/Code/flask-book/app/__init__.py:47]
2020-11-08 15:10:20,254 INFO: Microblog startup [in /Users/aaron/Code/flask-book/app/__init__.py:47]
2020-11-08 15:10:44,002 INFO: Microblog startup [in /Users/aaron/Code/flask-book/app/__init__.py:47]
2020-11-08 15:10:56,452 ERROR: Exception on /reset_password_request [POST] [in /Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aaron/Code/flask-book/app/routes.py", line 154, in reset_password_request
    send_password_reset_email(user)
  File "/Users/aaron/Code/flask-book/app/email.py", line 16, in send_password_reset_email
    text_body=render_template('email/reset_password.txt', user=user, token=token),
NameError: name 'render_template' is not defined
2020-11-08 15:11:31,767 INFO: Microblog startup [in /Users/aaron/Code/flask-book/app/__init__.py:47]
2020-11-08 15:11:45,036 ERROR: Exception on /reset_password_request [POST] [in /Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask_mail.py", line 188, in send
    self.host.sendmail(sanitize_address(envelope_from or message.sender),
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 856, in sendmail
    self.ehlo_or_helo_if_needed()
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 604, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 444, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 371, in putcmd
    self.send(str)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 363, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/aaron/Code/flask-book/app/routes.py", line 154, in reset_password_request
    send_password_reset_email(user)
  File "/Users/aaron/Code/flask-book/app/email.py", line 14, in send_password_reset_email
    send_mail('[Microblog] Reset Your Password',
  File "/Users/aaron/Code/flask-book/app/email.py", line 10, in send_mail
    mail.send(msg)
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/Users/aaron/Code/flask-book/venv/lib/python3.9/site-packages/flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 988, in quit
    res = self.docmd("quit")
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 424, in docmd
    self.putcmd(cmd, args)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 371, in putcmd
    self.send(str)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/smtplib.py", line 363, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
